site_name: Makers Bench
site_url: https://makers-bench.ch

nav:
  - Home: index.md
  - Our Journey: moving-toward-the-internet.md

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
